import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
from folium.plugins import HeatMap
from sklearn.cluster import DBSCAN
import os

# ==========================================
# PAGE CONFIG
# ==========================================
st.set_page_config(page_title="GridLock AI", layout="wide", page_icon="🚨")
st.title("🚦 GridLock AI — Urban Congestion Command Center")

# ==========================================
# LOAD DATA (From Person 1/2 outputs)
# ==========================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Updated path because app.py is now inside Frontend folder
file_path = os.path.join(BASE_DIR, "..", "Backend", "outputs", "cleaned_data_sample.csv")
zone_file = os.path.join(
    BASE_DIR,
    "..",
    "Backend",
    "outputs",
    "zone_full_data.csv"
)

@st.cache_data
def load_data():
    try:
        df = pd.read_csv(file_path)
        df = df.dropna(subset=["latitude", "longitude"])
        return df
    except FileNotFoundError:
        return pd.DataFrame()
    

def load_zone_data():
    try:
        return pd.read_csv(zone_file)
    except FileNotFoundError:
        return pd.DataFrame()

df = load_data()
zone_df = load_zone_data()
st.write(zone_df.head())

if df.empty:
    st.error("❌ Dataset not found! Make sure 'cleaned_data_sample.csv' is in Backend/outputs/")
else:
    # -------------------------
    # SIDEBAR CONTROLS
    # -------------------------
    st.sidebar.header("⚙️ Command Center Controls")
    heat_radius = st.sidebar.slider("Heatmap Intensity", 5, 25, 12)
    cluster_eps = st.sidebar.slider("Cluster Sensitivity (DBSCAN)", 0.001, 0.01, 0.003)
    show_heatmap = st.sidebar.checkbox("Show Heatmap", True)
    show_clusters = st.sidebar.checkbox("Show Hotspot Clusters", True)
    
    st.sidebar.markdown("---")
    st.sidebar.success("✅ ML Engine: Active")
    st.sidebar.success("✅ Geo Engine: Active")

    # -------------------------
    # TOP KPI METRICS
    # -------------------------
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Active Violations", len(df))
    high_risk = df[df["violation_list"].astype(str).str.contains("WRONG PARKING")].shape[0]
    col2.metric("Critical 'Wrong Parking' Zones", high_risk, delta="High Priority", delta_color="inverse")
    col3.metric("System Status", "Live Monitoring")
    st.markdown("---")

    # -------------------------
    # 3-TAB STRUCTURE (PERSON 3 MAIN TASK)
    # -------------------------
    tab1, tab2, tab3 = st.tabs(["🗺️ Live Congestion Map", "🟡 Spillover Risk Data", "🚨 Enforcement Priority"])

    # === TAB 1: PERSON 2'S MAP ===
    with tab1:
        st.subheader("Live City Congestion & Hotspots")
        
        # Base Map
        m = folium.Map(location=[df["latitude"].mean(), df["longitude"].mean()], zoom_start=12)
        
        # Heatmap Layer
        if show_heatmap:
            heat_data = df[["latitude", "longitude"]].values.tolist()
            HeatMap(heat_data, radius=heat_radius).add_to(m)
            
        # Clustering Layer
        if show_clusters:
            coords = df[["latitude", "longitude"]].values
            clustering = DBSCAN(eps=cluster_eps, min_samples=5).fit(coords)
            df["cluster"] = clustering.labels_
            for cluster_id in df["cluster"].unique():
                if cluster_id == -1: continue # skip noise
                cluster_points = df[df["cluster"] == cluster_id]
                folium.Circle(
                    location=[cluster_points["latitude"].mean(), cluster_points["longitude"].mean()],
                    radius=200, color="red", fill=True, fill_opacity=0.2,
                    popup=f"🔥 Hotspot Cluster {cluster_id}"
                ).add_to(m)

        # Violation Markers
        for _, row in df.iterrows():
            violation = str(row.get("violation_list", ""))
            if "WRONG PARKING" in violation:
                color, priority = "red", "HIGH RISK"
            elif "NO PARKING" in violation:
                color, priority = "orange", "MEDIUM RISK"
            else:
                color, priority = "blue", "LOW RISK"

            folium.CircleMarker(
                location=[row["latitude"], row["longitude"]],
                radius=6, color=color, fill=True, fill_opacity=0.7,
                popup=f"🚗 Vehicle: {row.get('vehicle_number','N/A')}<br>⚠️ Violation: {violation}<br>🚨 Priority: {priority}"
            ).add_to(m)

        # Render Map
        st_data = st_folium(m, width=1200, height=600)

    # === TAB 2: SPILLOVER RISK DATA ===
    with tab2:
        st.subheader("Raw Violation Data (ML Processed)")
        st.markdown("This table contains the extracted features and clustering labels generated by the ML engine.")
        # Ensure cluster column exists before showing
        if "cluster" not in df.columns:
            coords = df[["latitude", "longitude"]].values
            clustering = DBSCAN(eps=cluster_eps, min_samples=5).fit(coords)
            df["cluster"] = clustering.labels_
            
        st.dataframe(df, use_container_width=True)

    # === TAB 3: ENFORCEMENT PRIORITY ===
    with tab3:
        st.subheader("Targeted Enforcement Priority List")
        st.markdown("🚨 Dispatch tow trucks to these vehicles immediately to clear choke points.")
        
        # Priority Logic: Sort by WRONG PARKING first
        def get_priority_score(viol):
            if "WRONG PARKING" in str(viol): return 3
            if "NO PARKING" in str(viol): return 2
            return 1
            
        df['Action_Score'] = df['violation_list'].apply(get_priority_score)
        priority_df = df.sort_values(by="Action_Score", ascending=False).reset_index(drop=True)
        
        priority_df['Recommended_Action'] = priority_df['Action_Score'].map({
            3: "🚨 Tow Immediately",
            2: "🟡 Send Patrol",
            1: "🟢 Issue E-Challan"
        })
        
        display_cols = ['vehicle_number', 'violation_list', 'latitude', 'longitude', 'Recommended_Action']
        st.dataframe(priority_df[display_cols], use_container_width=True, hide_index=True)
